/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as storeLayoutRouteImport } from './routes/(store)/_layout'
import { Route as storeLayoutIndexRouteImport } from './routes/(store)/_layout/index'
import { Route as storeLayoutProfileRouteImport } from './routes/(store)/_layout/profile'
import { Route as storeLayoutOrdersRouteImport } from './routes/(store)/_layout/orders'
import { Route as storeLayoutOrderTrackingRouteImport } from './routes/(store)/_layout/order-tracking'
import { Route as storeLayoutOrderConfirmationRouteImport } from './routes/(store)/_layout/order-confirmation'
import { Route as storeLayoutCheckoutRouteImport } from './routes/(store)/_layout/checkout'
import { Route as storeLayoutCartRouteImport } from './routes/(store)/_layout/cart'
import { Route as storeLayoutStoreIndexRouteImport } from './routes/(store)/_layout/store/index'
import { Route as storeLayoutProductIndexRouteImport } from './routes/(store)/_layout/product/index'
import { Route as storeLayoutCategoryIndexRouteImport } from './routes/(store)/_layout/category/index'
import { Route as storeLayoutStoreSlugRouteImport } from './routes/(store)/_layout/store/$slug'
import { Route as storeLayoutProductProductIdRouteImport } from './routes/(store)/_layout/product/$productId'
import { Route as storeLayoutCategorySlugRouteImport } from './routes/(store)/_layout/category/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutRoute = storeLayoutRouteImport.update({
  id: '/(store)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutIndexRoute = storeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProfileRoute = storeLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutOrdersRoute = storeLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutOrderTrackingRoute =
  storeLayoutOrderTrackingRouteImport.update({
    id: '/order-tracking',
    path: '/order-tracking',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeLayoutOrderConfirmationRoute =
  storeLayoutOrderConfirmationRouteImport.update({
    id: '/order-confirmation',
    path: '/order-confirmation',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeLayoutCheckoutRoute = storeLayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutCartRoute = storeLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutStoreIndexRoute = storeLayoutStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProductIndexRoute = storeLayoutProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutCategoryIndexRoute =
  storeLayoutCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeLayoutStoreSlugRoute = storeLayoutStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProductProductIdRoute =
  storeLayoutProductProductIdRouteImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeLayoutCategorySlugRoute = storeLayoutCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => storeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart': typeof storeLayoutCartRoute
  '/checkout': typeof storeLayoutCheckoutRoute
  '/order-confirmation': typeof storeLayoutOrderConfirmationRoute
  '/order-tracking': typeof storeLayoutOrderTrackingRoute
  '/orders': typeof storeLayoutOrdersRoute
  '/profile': typeof storeLayoutProfileRoute
  '/': typeof storeLayoutIndexRoute
  '/category/$slug': typeof storeLayoutCategorySlugRoute
  '/product/$productId': typeof storeLayoutProductProductIdRoute
  '/store/$slug': typeof storeLayoutStoreSlugRoute
  '/category/': typeof storeLayoutCategoryIndexRoute
  '/product/': typeof storeLayoutProductIndexRoute
  '/store/': typeof storeLayoutStoreIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart': typeof storeLayoutCartRoute
  '/checkout': typeof storeLayoutCheckoutRoute
  '/order-confirmation': typeof storeLayoutOrderConfirmationRoute
  '/order-tracking': typeof storeLayoutOrderTrackingRoute
  '/orders': typeof storeLayoutOrdersRoute
  '/profile': typeof storeLayoutProfileRoute
  '/': typeof storeLayoutIndexRoute
  '/category/$slug': typeof storeLayoutCategorySlugRoute
  '/product/$productId': typeof storeLayoutProductProductIdRoute
  '/store/$slug': typeof storeLayoutStoreSlugRoute
  '/category': typeof storeLayoutCategoryIndexRoute
  '/product': typeof storeLayoutProductIndexRoute
  '/store': typeof storeLayoutStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/(store)/_layout': typeof storeLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/(store)/_layout/cart': typeof storeLayoutCartRoute
  '/(store)/_layout/checkout': typeof storeLayoutCheckoutRoute
  '/(store)/_layout/order-confirmation': typeof storeLayoutOrderConfirmationRoute
  '/(store)/_layout/order-tracking': typeof storeLayoutOrderTrackingRoute
  '/(store)/_layout/orders': typeof storeLayoutOrdersRoute
  '/(store)/_layout/profile': typeof storeLayoutProfileRoute
  '/(store)/_layout/': typeof storeLayoutIndexRoute
  '/(store)/_layout/category/$slug': typeof storeLayoutCategorySlugRoute
  '/(store)/_layout/product/$productId': typeof storeLayoutProductProductIdRoute
  '/(store)/_layout/store/$slug': typeof storeLayoutStoreSlugRoute
  '/(store)/_layout/category/': typeof storeLayoutCategoryIndexRoute
  '/(store)/_layout/product/': typeof storeLayoutProductIndexRoute
  '/(store)/_layout/store/': typeof storeLayoutStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/auth/sign-in'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/order-tracking'
    | '/orders'
    | '/profile'
    | '/'
    | '/category/$slug'
    | '/product/$productId'
    | '/store/$slug'
    | '/category/'
    | '/product/'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth/sign-in'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/order-tracking'
    | '/orders'
    | '/profile'
    | '/'
    | '/category/$slug'
    | '/product/$productId'
    | '/store/$slug'
    | '/category'
    | '/product'
    | '/store'
  id:
    | '__root__'
    | '/about'
    | '/(store)/_layout'
    | '/auth/sign-in'
    | '/(store)/_layout/cart'
    | '/(store)/_layout/checkout'
    | '/(store)/_layout/order-confirmation'
    | '/(store)/_layout/order-tracking'
    | '/(store)/_layout/orders'
    | '/(store)/_layout/profile'
    | '/(store)/_layout/'
    | '/(store)/_layout/category/$slug'
    | '/(store)/_layout/product/$productId'
    | '/(store)/_layout/store/$slug'
    | '/(store)/_layout/category/'
    | '/(store)/_layout/product/'
    | '/(store)/_layout/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  storeLayoutRoute: typeof storeLayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout': {
      id: '/(store)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/': {
      id: '/(store)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeLayoutIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/profile': {
      id: '/(store)/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof storeLayoutProfileRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/orders': {
      id: '/(store)/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof storeLayoutOrdersRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/order-tracking': {
      id: '/(store)/_layout/order-tracking'
      path: '/order-tracking'
      fullPath: '/order-tracking'
      preLoaderRoute: typeof storeLayoutOrderTrackingRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/order-confirmation': {
      id: '/(store)/_layout/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof storeLayoutOrderConfirmationRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/checkout': {
      id: '/(store)/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof storeLayoutCheckoutRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/cart': {
      id: '/(store)/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof storeLayoutCartRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/store/': {
      id: '/(store)/_layout/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof storeLayoutStoreIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/product/': {
      id: '/(store)/_layout/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof storeLayoutProductIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/category/': {
      id: '/(store)/_layout/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof storeLayoutCategoryIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/store/$slug': {
      id: '/(store)/_layout/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof storeLayoutStoreSlugRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/product/$productId': {
      id: '/(store)/_layout/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof storeLayoutProductProductIdRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/category/$slug': {
      id: '/(store)/_layout/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof storeLayoutCategorySlugRouteImport
      parentRoute: typeof storeLayoutRoute
    }
  }
}

interface storeLayoutRouteChildren {
  storeLayoutCartRoute: typeof storeLayoutCartRoute
  storeLayoutCheckoutRoute: typeof storeLayoutCheckoutRoute
  storeLayoutOrderConfirmationRoute: typeof storeLayoutOrderConfirmationRoute
  storeLayoutOrderTrackingRoute: typeof storeLayoutOrderTrackingRoute
  storeLayoutOrdersRoute: typeof storeLayoutOrdersRoute
  storeLayoutProfileRoute: typeof storeLayoutProfileRoute
  storeLayoutIndexRoute: typeof storeLayoutIndexRoute
  storeLayoutCategorySlugRoute: typeof storeLayoutCategorySlugRoute
  storeLayoutProductProductIdRoute: typeof storeLayoutProductProductIdRoute
  storeLayoutStoreSlugRoute: typeof storeLayoutStoreSlugRoute
  storeLayoutCategoryIndexRoute: typeof storeLayoutCategoryIndexRoute
  storeLayoutProductIndexRoute: typeof storeLayoutProductIndexRoute
  storeLayoutStoreIndexRoute: typeof storeLayoutStoreIndexRoute
}

const storeLayoutRouteChildren: storeLayoutRouteChildren = {
  storeLayoutCartRoute: storeLayoutCartRoute,
  storeLayoutCheckoutRoute: storeLayoutCheckoutRoute,
  storeLayoutOrderConfirmationRoute: storeLayoutOrderConfirmationRoute,
  storeLayoutOrderTrackingRoute: storeLayoutOrderTrackingRoute,
  storeLayoutOrdersRoute: storeLayoutOrdersRoute,
  storeLayoutProfileRoute: storeLayoutProfileRoute,
  storeLayoutIndexRoute: storeLayoutIndexRoute,
  storeLayoutCategorySlugRoute: storeLayoutCategorySlugRoute,
  storeLayoutProductProductIdRoute: storeLayoutProductProductIdRoute,
  storeLayoutStoreSlugRoute: storeLayoutStoreSlugRoute,
  storeLayoutCategoryIndexRoute: storeLayoutCategoryIndexRoute,
  storeLayoutProductIndexRoute: storeLayoutProductIndexRoute,
  storeLayoutStoreIndexRoute: storeLayoutStoreIndexRoute,
}

const storeLayoutRouteWithChildren = storeLayoutRoute._addFileChildren(
  storeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  storeLayoutRoute: storeLayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
