/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as storeLayoutRouteImport } from './routes/(store)/_layout'
import { Route as storeLayoutIndexRouteImport } from './routes/(store)/_layout/index'
import { Route as storeLayoutCartRouteImport } from './routes/(store)/_layout/cart'
import { Route as storeLayoutProductIndexRouteImport } from './routes/(store)/_layout/product/index'
import { Route as storeLayoutProductProductIdRouteImport } from './routes/(store)/_layout/product/$productId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutRoute = storeLayoutRouteImport.update({
  id: '/(store)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutIndexRoute = storeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutCartRoute = storeLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProductIndexRoute = storeLayoutProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProductProductIdRoute =
  storeLayoutProductProductIdRouteImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => storeLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart': typeof storeLayoutCartRoute
  '/': typeof storeLayoutIndexRoute
  '/product/$productId': typeof storeLayoutProductProductIdRoute
  '/product/': typeof storeLayoutProductIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart': typeof storeLayoutCartRoute
  '/': typeof storeLayoutIndexRoute
  '/product/$productId': typeof storeLayoutProductProductIdRoute
  '/product': typeof storeLayoutProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/(store)/_layout': typeof storeLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/(store)/_layout/cart': typeof storeLayoutCartRoute
  '/(store)/_layout/': typeof storeLayoutIndexRoute
  '/(store)/_layout/product/$productId': typeof storeLayoutProductProductIdRoute
  '/(store)/_layout/product/': typeof storeLayoutProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/auth/sign-in'
    | '/cart'
    | '/'
    | '/product/$productId'
    | '/product/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth/sign-in'
    | '/cart'
    | '/'
    | '/product/$productId'
    | '/product'
  id:
    | '__root__'
    | '/about'
    | '/(store)/_layout'
    | '/auth/sign-in'
    | '/(store)/_layout/cart'
    | '/(store)/_layout/'
    | '/(store)/_layout/product/$productId'
    | '/(store)/_layout/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  storeLayoutRoute: typeof storeLayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout': {
      id: '/(store)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/': {
      id: '/(store)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeLayoutIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/cart': {
      id: '/(store)/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof storeLayoutCartRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/product/': {
      id: '/(store)/_layout/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof storeLayoutProductIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/product/$productId': {
      id: '/(store)/_layout/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof storeLayoutProductProductIdRouteImport
      parentRoute: typeof storeLayoutRoute
    }
  }
}

interface storeLayoutRouteChildren {
  storeLayoutCartRoute: typeof storeLayoutCartRoute
  storeLayoutIndexRoute: typeof storeLayoutIndexRoute
  storeLayoutProductProductIdRoute: typeof storeLayoutProductProductIdRoute
  storeLayoutProductIndexRoute: typeof storeLayoutProductIndexRoute
}

const storeLayoutRouteChildren: storeLayoutRouteChildren = {
  storeLayoutCartRoute: storeLayoutCartRoute,
  storeLayoutIndexRoute: storeLayoutIndexRoute,
  storeLayoutProductProductIdRoute: storeLayoutProductProductIdRoute,
  storeLayoutProductIndexRoute: storeLayoutProductIndexRoute,
}

const storeLayoutRouteWithChildren = storeLayoutRoute._addFileChildren(
  storeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  storeLayoutRoute: storeLayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
